# Generated by Django 3.1 on 2020-08-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=30, verbose_name='Код предложения')),
                ('type', models.CharField(choices=[('co', 'Commercial offer'), ('bo', 'Business offer')], default='co', max_length=30)),
                ('project_hh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Часы на проектирование')),
                ('commissioning_hh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Часы на пусконаладку')),
                ('project_cost', models.FloatField(blank=True, verbose_name='Стоимость проектирования')),
                ('commissioning_cost', models.FloatField(blank=True, verbose_name='Стоимость пусконаладки')),
                ('material_cost', models.FloatField(blank=True, verbose_name='Стоимость материалов')),
                ('total_cost', models.FloatField(blank=True, verbose_name='Обащая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Предложенеие',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='DepartmentOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=30, verbose_name='Код предложения')),
                ('type', models.CharField(choices=[('co', 'Commercial offer'), ('bo', 'Business offer')], default='co', max_length=30, verbose_name='Тип')),
                ('project_hh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Часы на проектирование')),
                ('commissioning_hh', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Часы на пусконаладку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Предложенеие отдела',
                'verbose_name_plural': 'Предложения отделов',
            },
        ),
        migrations.CreateModel(
            name='ObjectCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ObjectsInOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Количество')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.objectcase', verbose_name='Объект')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.commercialoffer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Объект в предложении',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='DepartmentInCommercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Количество')),
                ('commercial_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.commercialoffer', verbose_name='Предложение')),
                ('department_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.departmentoffer', verbose_name='Предложение отдела')),
            ],
            options={
                'verbose_name': 'Предложении отдела',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='department_offer',
            field=models.ManyToManyField(blank=True, through='offers.DepartmentInCommercial', to='offers.DepartmentOffer', verbose_name='Предложение отдела'),
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='object_case',
            field=models.ManyToManyField(blank=True, through='offers.ObjectsInOffer', to='offers.ObjectCase', verbose_name='Объект'),
        ),
    ]
