# Generated by Django 3.1 on 2020-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialoffer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='departmentoffer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
