# Generated by Django 3.1 on 2020-09-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подразделение'),
        ),
    ]
