# Generated by Django 3.1 on 2020-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200924_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='make_it_by',
            field=models.DateField(null=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
