# Generated by Django 3.1 on 2020-09-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200926_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='income_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Код'),
        ),
    ]
