# Generated by Django 3.1 on 2020-08-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/departments/logos/', verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='DepartmentObjectCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Обьект',
                'verbose_name_plural': 'Обьекты',
            },
        ),
        migrations.CreateModel(
            name='DepartmentPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('skill', models.TextField(blank=True, verbose_name='Умения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/departments/photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='DepartmentObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Отдел')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departmentobjectcase', verbose_name='Обьект')),
            ],
            options={
                'verbose_name': 'Объект в предложении',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='object_case',
            field=models.ManyToManyField(blank=True, through='departments.DepartmentObjects', to='departments.DepartmentObjectCase', verbose_name='Объект'),
        ),
    ]
