# Generated by Django 3.1 on 2020-10-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20200926_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='object_case',
        ),
        migrations.AddField(
            model_name='departmentobjectcase',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
