# Generated by Django 3.1 on 2020-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20201005_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentobjectcase',
            name='object_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код обьекта'),
        ),
        migrations.AddField(
            model_name='departmentobjectcase',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
